### 게시글 생성 API
POST {{endpoint}}/api/boards
Content-Type: application/json

{
  "title": "title",
  "content": "content"
}

### 게시글 조회 API
GET {{endpoint}}/api/boards/1


### 게시글 목록 조회 API
GET {{endpoint}}/api/boards
