name: ec2 deploy with aws code deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github repository checkout
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 빌드
        run: ./gradlew clean build

      - name: Archive 파일명 가공
        run: mv ./build/libs/*SNAPSHOT.jar ./app.jar

      - name: ENV 파일 생성
        run: echo "${{ secrets.ENV_PROPERTIES }}" > ./.env

      - name: S3 파일 전송을 위한 압축
        run: tar -czvf $GITHUB_SHA.tar.gz app.jar appspec.yml deploy.sh .env

      - name: Github Actions에게 부여한 IAM User을 이용하여 AWS Resources에 접근하기 위한 Credential 설정
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: AWS Cli를 이용하여 S3에 압축 파일 전송
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://board-app-artifact/$GITHUB_SHA.tar.gz

      - name: CodeDeploy를 이용한 EC2 배포 프로세스 시작
        run: |
          aws deploy create-deployment \
            --application-name board-app \
            --deployment-group-name board-app-ec2 \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=board-app-artifact,bundleType=tgz,key=${GITHUB_SHA}.tar.gz
